name: DataMiner CICD Update Catalog Details

# Controls when the workflow will run
on:
  # push:
  #   branches:
  #     - main
  #     - master

  ## If you wish to only trigger on ReadMe changes. 
  ## Consider: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Catalog:
    runs-on: windows-latest
    steps:
      - name: Publish To Catalog
        env:
          DATAMINER_TOKEN: ${{ secrets.DATAMINER_TOKEN }}
        shell: pwsh
        run: |
          dotnet publish `
            -p:Version="1.1.0.2" `
            -p:VersionComment="Updating details" `
            -p:CatalogPublishKeyName="DATAMINER_TOKEN" `
            -c Release `
